### ISSUE TITLE
Using def to declare a variable breaks it's usability

### ISSUE THREAD

**Issue by rahulsom** [lappsgrid-incubator/jupyter-groovy-kernel#1]
This is an example of what works

<img width="1165" alt="working" src="https://cloud.githubusercontent.com/assets/193047/21628286/31a02e5e-d1d3-11e6-9c9e-ee8113e90b27.png">

However this does not work

<img width="1153" alt="breaking" src="https://cloud.githubusercontent.com/assets/193047/21628292/3b029716-d1d3-11e6-867a-af1424b922b8.png">

Is that expected?

**Comment by ksuderman** [comment]
Yes, this is the expected behavior, and it is a by product of the way variable scopes work in Groovy scripts. 

If you "define" a variable, either with **def** keyword or the type, then you get a variable that is only visible in the local scope (the Jupyter cell in this case).  If you omit the type definition then Groovy looks to the global binding (symbol table) and uses that.

```groovy
int a = 3 // Only accessible in the current cell
x = 3 //  A global variable accessible anywhere in the notebook.
```
